CREATE SCHEMA IF NOT EXISTS BR AUTHORIZATION qgis;
CREATE SCHEMA IF NOT EXISTS GE AUTHORIZATION qgis;
CREATE SCHEMA IF NOT EXISTS LC AUTHORIZATION qgis;
CREATE SCHEMA IF NOT EXISTS PS AUTHORIZATION qgis;
CREATE SCHEMA IF NOT EXISTS NL AUTHORIZATION qgis;
CREATE SCHEMA IF NOT EXISTS TEST AUTHORIZATION qgis;
CREATE SCHEMA IF NOT EXISTS GEOLOGY AUTHORIZATION qgis;
