name: Documentation publisher


env:
  PROJECT_FOLDER: "gml_application_schema_toolbox"
  PYTHON_VERSION: 3.7

on:
  push:
    branches: [ master ]
    paths:
      - 'docs/**/*'
      - '.github/workflows/doc2pages.yml'

jobs:
  doc-publisher:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements/documentation.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install project requirements
        run: |
          python -m pip install -U pip setuptools wheel
          python -m pip install -U -r requirements/documentation.txt

      - name: Build doc using Sphinx
        run: sphinx-build -b html docs docs/_build/html

      - uses: actions/upload-artifact@v2
        with:
          name: ${{ env.PROJECT_FOLDER }}-doc-latest
          path: docs/_build/html
          if-no-files-found: error

      - name: Deploy to GitHub Pages
        run: ghp-import --force --no-jekyll --push docs/_build/html
