name: "✅ Linter"

env:
  PROJECT_FOLDER: "gml_application_schema_toolbox"
  PYTHON_VERSION: 3.7

on:
  push:
    branches: [master]
    paths:
      - "**.py"
  pull_request:
    branches: [master]
    paths:
      - "**.py"

jobs:
  lint-py:
    name: Python 🐍
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup Python
        uses: actions/setup-python@v4.1.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements/*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install project requirements
        run: |
          python -m pip install -U pip setuptools wheel
          python -m pip install -U flake8

      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 ${{ env.PROJECT_FOLDER }} --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings.
          flake8 ${{ env.PROJECT_FOLDER }} --count --exit-zero --statistics
