name: "📦 Packager"

env:
  PROJECT_FOLDER: "gml_application_schema_toolbox"
  PYTHON_VERSION: 3.8

on:
  push:
    branches: [master]

jobs:
  packaging:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup Python
        uses: actions/setup-python@v4.2.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Cache dependencie
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements/*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install project requirements
        run: |
          python -m pip install -U pip setuptools wheel
          python -m pip install -U -r requirements/packaging.txt

      - name: Package the latest version
        run: |
          qgis-plugin-ci package --allow-uncommitted-changes latest

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ env.PROJECT_FOLDER }}-latest
          path: ${{ env.PROJECT_FOLDER }}.*.zip
          if-no-files-found: error
