name: Packager

env:
  PROJECT_FOLDER: "gml_application_schema_toolbox"
  PYTHON_VERSION: 3.8

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  packaging:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements/*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install project requirements
        run: |
          python -m pip install -U pip setuptools wheel
          python -m pip install -U 'qgis-plugin-ci>=1.8,<1.9'

      - name: Package the latest version
        run: |
          qgis-plugin-ci package latest

      - uses: actions/upload-artifact@v2
        with:
          name: ${{ env.PROJECT_FOLDER }}-latest
          path: ${{ env.PROJECT_FOLDER }}.latest.zip
          if-no-files-found: error
