name: "🚀 Release"

env:
  PROJECT_FOLDER: "gml_application_schema_toolbox"
  PYTHON_VERSION: 3.7

on:
  push:
    tags:
      - "*"

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4.2.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: "pip"
          cache-dependency-path: "requirements/packaging.txt"

      - name: Get tag name as version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Install project requirements
        run: |
          python -m pip install -U pip setuptools wheel
          python -m pip install -U -r requirements/packaging.txt

      - name: Get current changelog for ${VERSION}
        run: qgis-plugin-ci changelog ${GITHUB_REF/refs\/tags\//} >> release.md

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          fail_on_unmatched_files: true
          bodyFile: release.md
          generate_release_notes: true

      - name: Deploy plugin
        run: >-
          qgis-plugin-ci
          release ${GITHUB_REF/refs\/tags\//}
          --allow-uncommitted-changes
          --github-token ${{ secrets.GITHUB_TOKEN }}
          --osgeo-username ${{ secrets.OSGEO_USER }}
          --osgeo-password ${{ secrets.OSGEO_PASSWORD }}
